
%dw 2.0
output application/json 
---
[
  {
    "c_id": 17,
    "firstname": "Levi",
    "lastname": "Ackerman",
    "email": "levida.singh@example.com",
    "mailingstreet": "levi Street",
    "mailingcity": "Paradise",
    "mailingstate": "Haryana",
    "mailingcountry": "JApan",
    "leadsource": "Web",
    "title": "Titan Killer",
    "accountid": "001gL000008RGClQAO",
    "mailingpostalcode": "91234",
    "phone": "555-123-4567",
    "updated_at": "2025-07-10T10:58:59.566705"
  },
  {
    "c_id": 19,
    "firstname": "Ash",
    "lastname": "Ketcham",
    "email": "pikachu.singh@example.com",
    "mailingstreet": "pikachu Street",
    "mailingcity": "Paradise",
    "mailingstate": "Haryana",
    "mailingcountry": "JApan",
    "leadsource": "Web",
    "title": "Pokemon Lover",
    "accountid": "001gL000008RGClQAO",
    "mailingpostalcode": "91234",
    "phone": "555-123-4567",
    "updated_at": "2025-07-10T11:11:20.98398"
  },
  {
    "c_id": 20,
    "firstname": "Ash",
    "lastname": "Ketcham",
    "email": "pikachu.singh@example.com",
    "mailingstreet": "pikachu Street",
    "mailingcity": "Paradise",
    "mailingstate": "Haryana",
    "mailingcountry": "JApan",
    "leadsource": "Web",
    "title": "Pokemon Lover",
    "accountid": "001gL000008RGClQAO",
    "mailingpostalcode": "91234",
    "phone": "555-123-4567",
    "updated_at": "2025-07-10T11:11:33.981963"
  },
  {
    "c_id": 1,
    "firstname": "Pranjal",
    "lastname": "Choria",
    "email": "pc@gmail.com",
    "mailingstreet": "Thatipur,Morar",
    "mailingcity": "Gwalior",
    "mailingstate": "Madhya Pradesh",
    "mailingcountry": "India",
    "leadsource": "SDE-1",
    "title": "Software Engineer",
    "accountid": "001gL000008RGClQAO",
    "mailingpostalcode": "687687",
    "phone": "7897389334",
    "updated_at": "2025-07-09T17:37:59.545345"
  },
  {
    "c_id": 2,
    "firstname": "Parvendra",
    "lastname": "rajput",
    "email": "parvy@gmail.com",
    "mailingstreet": "Indore",
    "mailingcity": "Indore",
    "mailingstate": "Madhya Pradesh",
    "mailingcountry": "India",
    "leadsource": "SDE-2",
    "title": "Engineer",
    "accountid": "001gL000008RGClQAO",
    "mailingpostalcode": "98789g",
    "phone": "38983",
    "updated_at": "2025-07-09T17:37:59.545345"
  },
  {
    "c_id": 3,
    "firstname": "Parth",
    "lastname": "Soni",
    "email": "part@soni.com",
    "mailingstreet": "Arera Colony",
    "mailingcity": "Bhopal",
    "mailingstate": "Madhya Pradesh",
    "mailingcountry": "India",
    "leadsource": "SDE-1",
    "title": "Marketing",
    "accountid": "001gL000008RGClQAO",
    "mailingpostalcode": "78i789",
    "phone": "323242",
    "updated_at": "2025-07-09T17:37:59.545345"
  },
  {
    "c_id": 4,
    "firstname": "Sandeep",
    "lastname": "Koshti",
    "email": "sandy@gmail.com",
    "mailingstreet": "Koteshwara",
    "mailingcity": "Gwalior",
    "mailingstate": "Madhya Pradesh",
    "mailingcountry": "India",
    "leadsource": "SDE-1",
    "title": "Jr Engineer",
    "accountid": "001gL000008RGClQAO",
    "mailingpostalcode": "798798",
    "phone": "434324",
    "updated_at": "2025-07-09T17:37:59.545345"
  },
  {
    "c_id": 5,
    "firstname": "Koshi",
    "lastname": "choria",
    "email": "koshi@gmail.com",
    "mailingstreet": "Thatipur",
    "mailingcity": "Gwalior",
    "mailingstate": "Madhya Pradesh",
    "mailingcountry": "India",
    "leadsource": "Doctor",
    "title": "Doctor",
    "accountid": "001gL000008RGClQAO",
    "mailingpostalcode": "798789",
    "phone": "424324",
    "updated_at": "2025-07-09T17:37:59.545345"
  },
  {
    "c_id": 6,
    "firstname": "Ben",
    "lastname": "Tennyson",
    "email": "ben@universeboss.com",
    "mailingstreet": "California",
    "mailingcity": "New York",
    "mailingstate": "Arizona",
    "mailingcountry": "USA",
    "leadsource": "Hero TIme",
    "title": "Hero",
    "accountid": "001gL000008RGClQAO",
    "mailingpostalcode": "798789",
    "phone": "424324",
    "updated_at": "2025-07-09T17:37:59.545345"
  },
  {
    "c_id": 9,
    "firstname": "Parvendera",
    "lastname": "Bhopali",
    "email": "parvy.singh@example.com",
    "mailingstreet": "Yadav Street",
    "mailingcity": "Gurgaon",
    "mailingstate": "Haryana",
    "mailingcountry": "India",
    "leadsource": "Web",
    "title": "Software Engineer",
    "accountid": "001gL000008RGClQAO",
    "mailingpostalcode": "91234",
    "phone": "555-123-4567",
    "updated_at": "2025-07-10T00:28:45.100261"
  },
  {
    "c_id": 10,
    "firstname": "Parvendera",
    "lastname": "Indori",
    "email": "parvy.singh@example.com",
    "mailingstreet": "Yadav Street",
    "mailingcity": "Gurgaon",
    "mailingstate": "Haryana",
    "mailingcountry": "India",
    "leadsource": "Web",
    "title": "Software Engineer",
    "accountid": "001gL000008RGClQAO",
    "mailingpostalcode": "91234",
    "phone": "555-123-4567",
    "updated_at": "2025-07-10T00:31:39.763929"
  },
  {
    "c_id": 11,
    "firstname": "Parvendera",
    "lastname": "Indori",
    "email": "parvy.singh@example.com",
    "mailingstreet": "Yadav Street",
    "mailingcity": "Gurgaon",
    "mailingstate": "Haryana",
    "mailingcountry": "India",
    "leadsource": "Web",
    "title": "Software Engineer",
    "accountid": "001gL000008RGClQAO",
    "mailingpostalcode": "91234",
    "phone": "555-123-4567",
    "updated_at": "2025-07-10T00:34:06.660689"
  },
  {
    "c_id": 13,
    "firstname": "Eren",
    "lastname": "Yeager",
    "email": "eren.singh@example.com",
    "mailingstreet": "eren Street",
    "mailingcity": "Paradise",
    "mailingstate": "Haryana",
    "mailingcountry": "JApan",
    "leadsource": "Web",
    "title": "Software Engineer",
    "accountid": "001gL000008RGClQAO",
    "mailingpostalcode": "91234",
    "phone": "555-123-4567",
    "updated_at": "2025-07-10T01:37:34.308936"
  },
  {
    "c_id": 14,
    "firstname": "Eren",
    "lastname": "Yeager",
    "email": "eren.singh@example.com",
    "mailingstreet": "eren Street",
    "mailingcity": "Paradise",
    "mailingstate": "Haryana",
    "mailingcountry": "JApan",
    "leadsource": "Web",
    "title": "Software Engineer",
    "accountid": "001gL000008RGClQAO",
    "mailingpostalcode": "91234",
    "phone": "555-123-4567",
    "updated_at": "2025-07-10T01:39:43.44271"
  },
  {
    "c_id": 15,
    "firstname": "Levi",
    "lastname": "Ackerman",
    "email": "levida.singh@example.com",
    "mailingstreet": "levi Street",
    "mailingcity": "Paradise",
    "mailingstate": "Haryana",
    "mailingcountry": "JApan",
    "leadsource": "Web",
    "title": "Titan Killer",
    "accountid": "001gL000008RGClQAO",
    "mailingpostalcode": "91234",
    "phone": "555-123-4567",
    "updated_at": "2025-07-10T01:40:55.870461"
  }
]
